import = [
	"~/.config/alacritty/themes/themes/challenger_deep.toml"
 ]


[window]
padding.x = 10
padding.y = 8


[cursor]
style.shape = "beam"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"
